### ISSUE TITLE
Start foodadvisor strapi project with "npm run develop"

### ISSUE THREAD

**Issue by faheemhameed** [strapi/foodadvisor#112]
Hi there,

I am new to strapi CMS and now I am trying to run the foodadvisor strapi project by using the following command.

I had run npm install before the following:

```
$ npm run develop

> foodadvisor-v4@0.1.0 develop
> strapi develop

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Cannot find module 'react-select/animated'
Require stack:
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/admin/webpack.alias.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/admin/webpack.config.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/admin/utils/index.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/admin/index.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/strapi/lib/commands/builders/admin.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/strapi/lib/commands/builders/index.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/strapi/lib/commands/develop.js
- /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/strapi/bin/strapi.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/admin/webpack.alias.js:51:25
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/hameedbs/Projects/strapi-foodadvisor/httpdocs/api/node_modules/@strapi/admin/webpack.alias.js:50:12)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
```

Any help would be highly appreciated.

Many thanks.

**Comment by Mcastres** [comment]
Hello @faheemhameed 👋 
Are you still facing this issue? Do you have a public repo that I can check?
