### ISSUE TITLE
Node.js 18 - Error fetching localhost

### ISSUE THREAD

**Issue by Frost-on-Web** [strapi/foodadvisor#124]
Hello,

Not Strapi centered but I met an issue with the simple first "fetch" of the client application, eveything else was OK.

==> The responsible : **Node.js v18**

This is the "error" which can be logged from the Try/Catch :
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getServerSideProps (webpack-internal:///./pages/[[...slug]].js:61:21)
    at async Object.renderToHTML (C:\Dev\Projects\strapi-nextjs-foodadvisor-sample\foodadvisor\client\node_modules\next\dist\server\render.js:508:20)    
    at async doRender (C:\Dev\Projects\strapi-nextjs-foodadvisor-sample\foodadvisor\client\node_modules\next\dist\server\base-server.js:687:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (C:\Dev\Projects\strapi-nextjs-foodadvisor-sample\foodadvisor\client\node_modules\next\dist\server\base-server.js:796:28)
    at async C:\Dev\Projects\strapi-nextjs-foodadvisor-sample\foodadvisor\client\node_modules\next\dist\server\response-cache\index.js:80:36 {
  cause: Error: connect ECONNREFUSED ::1:1337
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 1337
  }
}
```

Hopefully i was already victim of this issue and i want to share the simple solution (found here) :
https://github.com/node-fetch/node-fetch/issues/1624

Rather than "localhost", you would prefer set up "127.0.0.1" into the API_URL config key :
```
# ./client/.env.development
# Rather than
NEXT_PUBLIC_API_URL=http://localhost:1337
# Prefer
NEXT_PUBLIC_API_URL=http://127.0.0.1:1337
```

Otherwize, thanks you for sharing this excellent demo !

**Comment by Mcastres** [comment]
Hello @Frost-on-Web 👋 

Thanks for the solution, unfortunately, we are also facing this issue with our website, and setting our localhost URL to 127.0.0.1 doesn't help... It seems that Next.js is having issues sometimes when doing external requests. I will close this for now. Feel free to re-open :)
