### ISSUE TITLE
Please update this starter with the latest Strapi, plugin and dependency versions

### ISSUE THREAD

**Issue by borzaka** [strapi/foodadvisor#140]
I tried to use this starter, and faced many problems during usage and upgrades:

- outdated Strapi and dep versions
- upgrading raises many issues: Node.js version mismatch, plugin versions mismatch, failed build (`Cannot find module '@webbio/strapi-plugin-scheduler/cron-task'`), etc.
- many npm WARN and deprecated messages
- after some unsuccessful attempt, the admin panel starts, but there are unregular errors: editing an article throws an error: http://localhost:1337/admin/content-manager/collection-types/api::article.article/3?plugins%5Bi18n%5D%5Blocale%5D=en 
```
main.663d6551.js:1154 Uncaught 
ReferenceError: process is not defined
    at Zn (main.663d6551.js:1154:7252)
    at gl (main.663d6551.js:2047:18075)
    at Zc (main.663d6551.js:2049:45886)
    at Eh (main.663d6551.js:2049:41468)
    at Ou (main.663d6551.js:2049:41396)
    at Vd (main.663d6551.js:2049:41247)
    at gh (main.663d6551.js:2049:37461)
    at mh (main.663d6551.js:2049:36357)
    at X (main.663d6551.js:2141:1646)
    at MessagePort.Q (main.663d6551.js:2141:2025)
```
- other pages throws and error as well: BlogPage, Global, RestaurantPage

My updated package.json dependencies list:
```json
  "dependencies": {
    "@ckeditor/strapi-plugin-ckeditor": "^0.0.11",
    "@offset-dev/strapi-calendar": "^0.0.10",
    "@strapi/plugin-graphql": "4.25.0",
    "@strapi/plugin-i18n": "4.25.0",
    "@strapi/plugin-seo": "^1.9.8",
    "@strapi/plugin-users-permissions": "4.25.0",
    "@strapi/strapi": "4.25.0",
    "@webbio/strapi-plugin-scheduler": "^1.0.6",
    "better-sqlite3": "^11.0.0",
    "fs-extra": "^11.2.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^5.3.4",
    "strapi-plugin-populate-deep": "^3.0.1",
    "strapi-plugin-todo": "^0.0.10",
    "styled-components": "^5.3.3",
    "unzip-stream": "^0.3.4",
    "uuid-v4": "^0.1.0"
  },
```
I have removed the `engines` key. And I'am using Node.js 18.19.1

In the current state, it's a very bad developer experience.

**Comment by sgalcheung** [comment]
I used npm version 16.20.2, it worked well.
