### ISSUE TITLE
Deleting the Restaurant content type breaks the app

### ISSUE THREAD

**Issue by pierreburgy** [strapi/foodadvisor#59]
Deleting the Restaurant content type breaks the app.

Steps to reproduce:
 - Go to the Content-Types Builder.
 - Click on the "Restaurant" Content-Type.
 - Click on the "pen" icon.
 - Delete the Content-Type.

Strapi version: 3.2.5
OS: MacOS 10.14.6
Database: SQLite (with seed data)

The server stops with the error below:

```
[2020-11-02T11:17:59.034Z] error Error: Cannot extend type "Restaurant" because it is not defined. Did you mean "RestaurantNote"?
    at assertValidSDLExtension (/Users/pierreburgy/Desktop/foodadvisor/api/node_modules/graphql/validation/validate.js:124:11)
    at Object.extendSchema (/Users/pierreburgy/Desktop/foodadvisor/api/node_modules/graphql/utilities/extendSchema.js:77:43)
    at Object.buildSchemaFromTypeDefinitions (/Users/pierreburgy/Desktop/foodadvisor/api/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:29:28)
    at makeExecutableSchema (/Users/pierreburgy/Desktop/foodadvisor/api/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/pierreburgy/Desktop/foodadvisor/api/node_modules/strapi-plugin-graphql/services/schema-generator.js:98:20)
    at Object.initialize (/Users/pierreburgy/Desktop/foodadvisor/api/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:81:9)
    at /Users/pierreburgy/Desktop/foodadvisor/api/node_modules/strapi/lib/hooks/index.js:37:28
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vcoisne** [comment]
@Mcastres should we close this ?

**Comment by Mcastres** [comment]
Yes
