### ISSUE TITLE
Cannot compile and first run CMS

### ISSUE THREAD

**Issue by lack-of-gravitas** [strapi/foodadvisor#92]
Followed instructions to clone the repo (and made sure .env file existed with correct variables). When running yarn seed && yarn develop the following error is encountered.

Node14.18.1 // npm 6.14.5 // yarn  1.22.17 on windows 10

```
[5/5] Building fresh packages...
success Saved lockfile.
Done in 141.19s.
yarn run v1.22.17
$ node scripts/seed.js
Failed to move C:\Users\lack-of-gravitas\praxio\foodadvisor\cms\data\uploads to  public\uploads
Done in 0.71s.
yarn run v1.22.17
$ strapi develop
[2021-11-16T07:16:39.119Z] debug ⛔️ Server wasn't able to start properly.
[2021-11-16T07:16:39.121Z] error C:\Users\lack-of-gravitas\praxio\foodadvisor\cms\node_modules\parse5\lib\tokenizer\index.js:1
?'
^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\lack-of-gravitas\praxio\foodadvisor\cms\node_modules\parse5\lib\parser\index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Mcastres** [comment]
Hey @lack-of-gravitas, do you still have this issue?

**Comment by lack-of-gravitas** [comment]
yep still having this issue for some reason -- I think it has to do with my local machine config -- tried it on a separate wintel laptop instead and it worked fine
