### ISSUE TITLE
ENAMETOOLONG when trying to seed project

### ISSUE THREAD

**Issue by claesenm** [strapi/foodadvisor#94]
I consistently get errors when trying to seed this demo project, both using yarn and npm. After pulling this repo, I've followed the instructions as per the README. 

The error I'm getting is as follows:

```
$ npm run seed

> foodadvisor-api@0.1.0 seed /home/claesenm/IdeaProjects/foodadvisor/api
> node scripts/seed.js

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: ENAMETOOLONG: name too long, open 'data/uploads/small_14567577_1598088933819868_618245593398930877_o_jpg_nc_cat_102_and_ccb_1_3_and_nc_sid_e3f864_and_nc_ohc_Wy7_N98_Cc_Nm4_AX_8fs_Rou_and_nc_ht_scontent_cdg2_1_a46e8e491a.xx&oh=035daa982eb48eef8a13d92d42f59d4d&oe=60E4E301'
Emitted 'error' event on Extract instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: 'data/uploads/small_14567577_1598088933819868_618245593398930877_o_jpg_nc_cat_102_and_ccb_1_3_and_nc_sid_e3f864_and_nc_ohc_Wy7_N98_Cc_Nm4_AX_8fs_Rou_and_nc_ht_scontent_cdg2_1_a46e8e491a.xx&oh=035daa982eb48eef8a13d92d42f59d4d&oe=60E4E301'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foodadvisor-api@0.1.0 seed: `node scripts/seed.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foodadvisor-api@0.1.0 seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/claesenm/.npm/_logs/2021-11-17T10_03_15_977Z-debug.log
```

Environment details:
- OS: Ubuntu 20.04
- npm version 6.14.14
- node version 14.17.5
- commit `5f541df7ce7d1c0d39336c55f396c32f45ff2977`

**Comment by Mcastres** [comment]
Hey @claesenm, are you on Windows?

**Comment by claesenm** [comment]
No, I'm on Ubuntu 20.04. Is there any kind of npm configuration or env variable I could set to limit filenames?

**Comment by halise33a** [comment]
Are you able to proportion your .Tale file so that we are able to have a look at the triggers, settings, and alternatives you've got delivered? It may be something very simple to get guidance on [this article](https://electricsmokersinfo.com/), however those are constantly much simpler to parent out while the Storyline course is shared.
